
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class AddProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddProductPanel
     */
    public AddProductPanel() {
        initComponents();
        
        conn = MySqlConnect.connectDB();
        
        refreshAddCategory();
    }
    
    private void refreshAddCategory(){
        try {
            jcbCategory.removeAllItems();
            sql = "SELECT categoryname from category";
            statement = conn.createStatement();
            rs = statement.executeQuery(sql);
            
            while (rs.next()) {
                jcbCategory.addItem(rs.getString(1));
            }
            jcbCategory.setSelectedIndex(-1);
        } catch (Exception e) {
        }finally{
            try {
                rs.close();
                statement.close();
            } catch (Exception e) {
            }
        }
    }
    
    private void clearFields(){
        txtProductName.setText("");
        txtQuantity.setText("");
        txtIgst.setText("0");
        txtCgst.setText("0");
        txtSgst.setText("0");
        txtCost.setText("");
        txtStock.setText("");
        jcbCategory.setSelectedIndex(-1);
    }

    private float percentageCal(float value, float percentage){
        float ans = value*(percentage/100.0f);
        return ans;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jspProductName = new javax.swing.JSeparator();
        txtQuantity = new javax.swing.JTextField();
        jspQuantity = new javax.swing.JSeparator();
        btnAddCategory = new javax.swing.JButton();
        lblIgst = new javax.swing.JLabel();
        txtIgst = new javax.swing.JTextField();
        jspStock = new javax.swing.JSeparator();
        lblCategoryName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jcbCategory = new javax.swing.JComboBox<>();
        lblStock1 = new javax.swing.JLabel();
        txtCgst = new javax.swing.JTextField();
        jspStock1 = new javax.swing.JSeparator();
        lblStock2 = new javax.swing.JLabel();
        txtSgst = new javax.swing.JTextField();
        jspStock2 = new javax.swing.JSeparator();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jspStock3 = new javax.swing.JSeparator();
        lblCost = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jspQuantity1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(29, 35, 59));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductName.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblProductName.setText("Product Name");
        add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 200, 40));

        lblQuantity.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity ");
        add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 40));

        txtProductName.setBackground(new java.awt.Color(29, 35, 59));
        txtProductName.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtProductName.setForeground(new java.awt.Color(0, 246, 237));
        txtProductName.setBorder(null);
        txtProductName.setCaretColor(new java.awt.Color(0, 246, 237));
        txtProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProductNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProductNameFocusLost(evt);
            }
        });
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });
        add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 320, -1));

        jspProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jspProductNameFocusGained(evt);
            }
        });
        add(jspProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 320, 10));

        txtQuantity.setBackground(new java.awt.Color(29, 35, 59));
        txtQuantity.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(0, 246, 237));
        txtQuantity.setBorder(null);
        txtQuantity.setCaretColor(new java.awt.Color(0, 246, 237));
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 320, -1));
        add(jspQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 320, 10));

        btnAddCategory.setBackground(new java.awt.Color(29, 35, 59));
        btnAddCategory.setFont(new java.awt.Font("Share Tech Mono", 1, 14)); // NOI18N
        btnAddCategory.setForeground(new java.awt.Color(0, 246, 237));
        btnAddCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });
        add(btnAddCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 40, 40));

        lblIgst.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblIgst.setForeground(new java.awt.Color(255, 255, 255));
        lblIgst.setText("IGST");
        add(lblIgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 170, 30));

        txtIgst.setBackground(new java.awt.Color(29, 35, 59));
        txtIgst.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtIgst.setForeground(new java.awt.Color(0, 246, 237));
        txtIgst.setText("0");
        txtIgst.setBorder(null);
        txtIgst.setCaretColor(new java.awt.Color(0, 246, 237));
        txtIgst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIgstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIgstFocusLost(evt);
            }
        });
        add(txtIgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 320, -1));
        add(jspStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 320, 10));

        lblCategoryName.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCategoryName.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryName.setText("Category Name");
        add(lblCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 40));

        btnAdd.setBackground(new java.awt.Color(29, 35, 59));
        btnAdd.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 246, 237));
        btnAdd.setText(" ADD");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 140, 50));

        jcbCategory.setBackground(new java.awt.Color(29, 35, 59));
        jcbCategory.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        jcbCategory.setForeground(new java.awt.Color(0, 246, 237));
        jcbCategory.setToolTipText("");
        jcbCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 246, 237)));
        jcbCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jcbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 320, 35));

        lblStock1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblStock1.setForeground(new java.awt.Color(255, 255, 255));
        lblStock1.setText("CGST");
        add(lblStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 170, 30));

        txtCgst.setBackground(new java.awt.Color(29, 35, 59));
        txtCgst.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCgst.setForeground(new java.awt.Color(0, 246, 237));
        txtCgst.setText("0");
        txtCgst.setBorder(null);
        txtCgst.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCgst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCgstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCgstFocusLost(evt);
            }
        });
        add(txtCgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 320, -1));
        add(jspStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 320, 10));

        lblStock2.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblStock2.setForeground(new java.awt.Color(255, 255, 255));
        lblStock2.setText("SGST");
        add(lblStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 170, 30));

        txtSgst.setBackground(new java.awt.Color(29, 35, 59));
        txtSgst.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtSgst.setForeground(new java.awt.Color(0, 246, 237));
        txtSgst.setText("0");
        txtSgst.setBorder(null);
        txtSgst.setCaretColor(new java.awt.Color(0, 246, 237));
        txtSgst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSgstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSgstFocusLost(evt);
            }
        });
        add(txtSgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 320, -1));
        add(jspStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 320, 10));

        lblStock.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        lblStock.setText("Stock");
        add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 170, 30));

        txtStock.setBackground(new java.awt.Color(29, 35, 59));
        txtStock.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtStock.setForeground(new java.awt.Color(0, 246, 237));
        txtStock.setBorder(null);
        txtStock.setCaretColor(new java.awt.Color(0, 246, 237));
        txtStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStockFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStockFocusLost(evt);
            }
        });
        add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 320, -1));
        add(jspStock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 320, 10));

        lblCost.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCost.setForeground(new java.awt.Color(255, 255, 255));
        lblCost.setText("Cost");
        add(lblCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 150, 40));

        txtCost.setBackground(new java.awt.Color(29, 35, 59));
        txtCost.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCost.setForeground(new java.awt.Color(0, 246, 237));
        txtCost.setBorder(null);
        txtCost.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCostFocusLost(evt);
            }
        });
        add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 320, -1));
        add(jspQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 320, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProductNameFocusGained
        jspProductName.setBackground(new Color(0,246,237));
        jspProductName.setForeground(new Color(0,246,237));
        lblProductName.setForeground(new Color(0,246,237));
    }//GEN-LAST:event_txtProductNameFocusGained

    private void txtProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProductNameFocusLost
        jspProductName.setBackground(new Color(255,250,255));
        jspProductName.setForeground(new Color(255,250,255));
        lblProductName.setForeground(new Color(255,250,255));
    }//GEN-LAST:event_txtProductNameFocusLost

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void jspProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jspProductNameFocusGained

    }//GEN-LAST:event_jspProductNameFocusGained

    private void txtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusGained
        jspQuantity.setBackground(new Color(0,246,237));
        jspQuantity.setForeground(new Color(0,246,237));
        lblQuantity.setForeground(new Color(0,246,237));
    }//GEN-LAST:event_txtQuantityFocusGained

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        jspQuantity.setBackground(new Color(255,250,255));
        jspQuantity.setForeground(new Color(255,250,255));
        lblQuantity.setForeground(new Color(255,250,255));
    }//GEN-LAST:event_txtQuantityFocusLost

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        inputCategory = JOptionPane.showInputDialog(this, "Enter a category");
        if (inputCategory.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a category!");
        } else {
            String sql = "INSERT INTO category (categoryname) VALUES (?)";
            try {
                preparedStatement = conn.prepareStatement(sql);

                preparedStatement.setString(1, inputCategory);

                boolean stmt = preparedStatement.execute();
                JOptionPane.showMessageDialog(null, "Record Saved Successfully");

                refreshAddCategory();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Some Error : " + e);
            }
            finally{
                try {
                    preparedStatement.close();
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void txtIgstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIgstFocusGained
        jspStock.setBackground(new Color(0,246,237));
        jspStock.setForeground(new Color(0,246,237));
        lblIgst.setForeground(new Color(0,246,237));
    }//GEN-LAST:event_txtIgstFocusGained

    private void txtIgstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIgstFocusLost
        jspStock.setBackground(new Color(255,250,255));
        jspStock.setForeground(new Color(255,250,255));
        lblIgst.setForeground(new Color(255,250,255));
    }//GEN-LAST:event_txtIgstFocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //JOptionPane.showMessageDialog(null, "test");
        try {
            String sql = "SELECT categoryid FROM category WHERE categoryname = '" + jcbCategory.getSelectedItem().toString() + "'";
            statement = conn.createStatement();
            rs = statement.executeQuery(sql);
            
            while(rs.next()){
                catID = rs.getInt(1);
                System.out.println(catID);
            }
           
            if(txtProductName.getText().equals("") || txtQuantity.getText().equals("") ||  txtIgst.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Some Fields are missing");
            }
            else{
                
                sql = "INSERT INTO product( productname, mass, cost, cgst, sgst, igst, mrp, stock, categoryid) VALUES (?,?,?,?,?,?,?,?,?)";
                preparedStatement = conn.prepareStatement(sql);
                
                float cost = Float.parseFloat(txtCost.getText());
                float  cgst = Float.parseFloat(txtCgst.getText());
                float sgst = Float.parseFloat(txtSgst.getText());
                float igst = Float.parseFloat(txtIgst.getText());

                preparedStatement.setString(1, txtProductName.getText());
                preparedStatement.setString(2, txtQuantity.getText());
                preparedStatement.setFloat(3, cost);
                preparedStatement.setFloat(4, cgst);
                preparedStatement.setFloat(5, sgst);
                preparedStatement.setFloat(6, igst);
                preparedStatement.setFloat(7, (cost + (percentageCal(cost, cgst) + percentageCal(cost, sgst) + percentageCal(cost, igst))));
                preparedStatement.setString(8, txtStock.getText());
                preparedStatement.setInt(9, catID);
                
                boolean stmt = preparedStatement.execute();
                
                JOptionPane.showMessageDialog(null, "Sucessfully inserted!!");
            }
            clearFields();
            
        }catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Some Error : " + e);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    
    
    
    private void txtCgstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCgstFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCgstFocusGained

    private void txtCgstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCgstFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCgstFocusLost

    private void txtSgstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSgstFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSgstFocusGained

    private void txtSgstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSgstFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSgstFocusLost

    private void txtStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStockFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockFocusGained

    private void txtStockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStockFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockFocusLost

    private void txtCostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostFocusGained

    private void txtCostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCostFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JComboBox<String> jcbCategory;
    private javax.swing.JSeparator jspProductName;
    private javax.swing.JSeparator jspQuantity;
    private javax.swing.JSeparator jspQuantity1;
    private javax.swing.JSeparator jspStock;
    private javax.swing.JSeparator jspStock1;
    private javax.swing.JSeparator jspStock2;
    private javax.swing.JSeparator jspStock3;
    private javax.swing.JLabel lblCategoryName;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblIgst;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblStock1;
    private javax.swing.JLabel lblStock2;
    private javax.swing.JTextField txtCgst;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtIgst;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSgst;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
    private Connection conn = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet rs = null;
    private Statement statement;
    private String inputCategory = null;
    private int catID ;
    private String sql = null;
    private int selectedRow;
    private String selectedProductId;

}
