
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import jiconfont.icons.Elusive;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shubham
 */
public class CustomerForm extends javax.swing.JPanel implements Constants{

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
        conn = MySqlConnect.connectDB();
        sql = "SELECT * FROM customer";
        updateTableData(sql);
        IconFontSwing.register(FontAwesome.getIconFont());
        IconFontSwing.register(Elusive.getIconFont());
        btnAdd.setIcon(IconFontSwing.buildIcon(Constants.addButton, 30, Constants.LIGHT_BLUE));
        btnUpdate.setIcon(IconFontSwing.buildIcon(Constants.updateButton, 30, Constants.LIGHT_BLUE));
        btnDelete.setIcon(IconFontSwing.buildIcon(Constants.deleteButton, 30, Constants.LIGHT_BLUE));
        btnClear.setIcon(IconFontSwing.buildIcon(Constants.clearButton, 30, Constants.LIGHT_BLUE));
        
        
        //add document listener to email text field
        txtCustEmail.getDocument().addDocumentListener(new DocumentListener(){ 
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkEmail();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkEmail();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void clearFields(){
        txtCustName.setText(""); 
        txtCustContact.setText("");
        txtcustGST.setText("");
        txtCustEmail.setText("");
        jspEmail.setBackground(Constants.WHITE);
        jspEmail.setForeground(Constants.WHITE);
    }
    
     void updateTableData(String sql){
        try {
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jtbData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Issue : " + e);
        }
        finally{
            try {
                rs.close();
                preparedStatement.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Problem in closing rs or prepared statement :  " + e);
            }
        }
    }
     
     private void checkEmail(){
        String emailPatternString = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-\\+]+)*@[_A-Za-z0-9-]+(\\.A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
	Pattern emailPattern = Pattern.compile(emailPatternString);
	Matcher emailMatcher = emailPattern.matcher(txtCustEmail.getText());
	if(emailMatcher.matches()){
            txtCustEmail.setForeground(Constants.LIGHT_BLUE);
            jspEmail.setBackground(Constants.LIGHT_BLUE);
            jspEmail.setForeground(Constants.LIGHT_BLUE);
        }
        else{
            txtCustEmail.setForeground(Constants.RED);
            jspEmail.setBackground(Constants.RED);
            jspEmail.setForeground(Constants.RED);
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustEmail = new javax.swing.JTextField();
        jspEmail = new javax.swing.JSeparator();
        lblCustContact = new javax.swing.JLabel();
        lblCustGST = new javax.swing.JLabel();
        lblCustEmail = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        jspName = new javax.swing.JSeparator();
        txtCustContact = new javax.swing.JTextField();
        jspContact = new javax.swing.JSeparator();
        txtcustGST = new javax.swing.JTextField();
        jspGST = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable()
        ;
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtCustEmail1 = new javax.swing.JTextField();
        lblcust = new javax.swing.JLabel();
        jspEmail1 = new javax.swing.JSeparator();
        lblCustContact1 = new javax.swing.JLabel();
        lblCustGST1 = new javax.swing.JLabel();
        lblCustEmail1 = new javax.swing.JLabel();
        txtCustName1 = new javax.swing.JTextField();
        jspName1 = new javax.swing.JSeparator();
        txtCustContact1 = new javax.swing.JTextField();
        jspContact1 = new javax.swing.JSeparator();
        txtcustGST1 = new javax.swing.JTextField();
        jspGST1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbData1 = new javax.swing.JTable()
        ;
        btnUpdate1 = new javax.swing.JButton();
        btnDelete1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        btnAdd1 = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 35, 59));
        setForeground(new java.awt.Color(255, 250, 255));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1820, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCustEmail.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCustEmail.setForeground(new java.awt.Color(0, 246, 237));
        txtCustEmail.setBorder(null);
        txtCustEmail.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCustEmail.setOpaque(false);
        txtCustEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustEmailFocusLost(evt);
            }
        });
        txtCustEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustEmailActionPerformed(evt);
            }
        });
        add(txtCustEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 520, 400, -1));

        jspEmail.setBackground(new java.awt.Color(255, 250, 255));
        jspEmail.setForeground(new java.awt.Color(255, 250, 255));
        add(jspEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 410, -1));

        lblCustContact.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCustContact.setForeground(new java.awt.Color(255, 250, 255));
        lblCustContact.setText("Contact  ");
        lblCustContact.setToolTipText("");
        add(lblCustContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        lblCustGST.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCustGST.setForeground(new java.awt.Color(255, 250, 255));
        lblCustGST.setText("GST NO. ");
        lblCustGST.setToolTipText("");
        add(lblCustGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        lblCustEmail.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCustEmail.setForeground(new java.awt.Color(255, 250, 255));
        lblCustEmail.setText("Email ID ");
        lblCustEmail.setToolTipText("");
        add(lblCustEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        txtCustName.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCustName.setForeground(new java.awt.Color(0, 246, 237));
        txtCustName.setBorder(null);
        txtCustName.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCustName.setOpaque(false);
        txtCustName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustNameFocusLost(evt);
            }
        });
        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });
        add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 340, 400, -1));

        jspName.setBackground(new java.awt.Color(255, 250, 255));
        jspName.setForeground(new java.awt.Color(255, 250, 255));
        add(jspName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 410, -1));

        txtCustContact.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCustContact.setForeground(new java.awt.Color(0, 246, 237));
        txtCustContact.setBorder(null);
        txtCustContact.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCustContact.setOpaque(false);
        txtCustContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustContactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustContactFocusLost(evt);
            }
        });
        txtCustContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustContactActionPerformed(evt);
            }
        });
        add(txtCustContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 400, 400, -1));

        jspContact.setBackground(new java.awt.Color(255, 250, 255));
        jspContact.setForeground(new java.awt.Color(255, 250, 255));
        add(jspContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 410, -1));

        txtcustGST.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtcustGST.setForeground(new java.awt.Color(0, 246, 237));
        txtcustGST.setBorder(null);
        txtcustGST.setCaretColor(new java.awt.Color(0, 246, 237));
        txtcustGST.setOpaque(false);
        txtcustGST.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcustGSTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcustGSTFocusLost(evt);
            }
        });
        txtcustGST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustGSTActionPerformed(evt);
            }
        });
        add(txtcustGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 460, 400, -1));

        jspGST.setBackground(new java.awt.Color(255, 250, 255));
        jspGST.setForeground(new java.awt.Color(255, 250, 255));
        add(jspGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 410, -1));

        jScrollPane1.setBackground(new java.awt.Color(29, 35, 59));
        jScrollPane1.setForeground(new java.awt.Color(29, 35, 59));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtbData.setBackground(new java.awt.Color(29, 35, 59));
        jtbData.setFont(new java.awt.Font("Share Tech Mono", 0, 18)); // NOI18N
        jtbData.setForeground(new java.awt.Color(0, 246, 237));
        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbData.setFocusable(false);
        jtbData.setGridColor(new java.awt.Color(0, 246, 237));
        jtbData.setOpaque(false);
        jtbData.setRowHeight(30);
        jtbData.setRowMargin(2);
        jtbData.setSelectionBackground(new java.awt.Color(0, 246, 237));
        jtbData.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jtbData.getTableHeader().setResizingAllowed(false);
        jtbData.getTableHeader().setReorderingAllowed(false);
        jtbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbData);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 710, -1));

        btnUpdate.setBackground(new java.awt.Color(29, 35, 59));
        btnUpdate.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 246, 237));
        btnUpdate.setText(" UPDATE");
        btnUpdate.setActionCommand("UPDATE");
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 760, 140, 50));

        btnDelete.setBackground(new java.awt.Color(29, 35, 59));
        btnDelete.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 246, 237));
        btnDelete.setText(" DELETE");
        btnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 760, 140, 50));

        btnClear.setBackground(new java.awt.Color(29, 35, 59));
        btnClear.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 246, 237));
        btnClear.setText(" CLEAR");
        btnClear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setNextFocusableComponent(txtCustName);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 760, 140, 50));

        btnAdd.setBackground(new java.awt.Color(29, 35, 59));
        btnAdd.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 246, 237));
        btnAdd.setText(" ADD");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddMouseReleased(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 760, 140, 50));

        jPanel1.setBackground(new java.awt.Color(29, 35, 59));
        jPanel1.setForeground(new java.awt.Color(255, 250, 255));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(1820, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCustEmail1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCustEmail1.setForeground(new java.awt.Color(0, 246, 237));
        txtCustEmail1.setBorder(null);
        txtCustEmail1.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCustEmail1.setOpaque(false);
        txtCustEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustEmail1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustEmail1FocusLost(evt);
            }
        });
        txtCustEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustEmail1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCustEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 520, 400, -1));

        lblcust.setFont(new java.awt.Font("Share Tech Mono", 0, 55)); // NOI18N
        lblcust.setForeground(new java.awt.Color(255, 250, 255));
        lblcust.setText("Customer Form ");
        jPanel1.add(lblcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 550, 190));

        jspEmail1.setBackground(new java.awt.Color(255, 250, 255));
        jspEmail1.setForeground(new java.awt.Color(255, 250, 255));
        jPanel1.add(jspEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 410, -1));

        lblCustContact1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCustContact1.setForeground(new java.awt.Color(255, 250, 255));
        lblCustContact1.setText("Contact  ");
        lblCustContact1.setToolTipText("");
        jPanel1.add(lblCustContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        lblCustGST1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCustGST1.setForeground(new java.awt.Color(255, 250, 255));
        lblCustGST1.setText("GST NO. ");
        lblCustGST1.setToolTipText("");
        jPanel1.add(lblCustGST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        lblCustEmail1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblCustEmail1.setForeground(new java.awt.Color(255, 250, 255));
        lblCustEmail1.setText("Email ID ");
        lblCustEmail1.setToolTipText("");
        jPanel1.add(lblCustEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        txtCustName1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCustName1.setForeground(new java.awt.Color(0, 246, 237));
        txtCustName1.setBorder(null);
        txtCustName1.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCustName1.setOpaque(false);
        txtCustName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustName1FocusLost(evt);
            }
        });
        txtCustName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustName1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCustName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 340, 400, -1));

        jspName1.setBackground(new java.awt.Color(255, 250, 255));
        jspName1.setForeground(new java.awt.Color(255, 250, 255));
        jPanel1.add(jspName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 410, -1));

        txtCustContact1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtCustContact1.setForeground(new java.awt.Color(0, 246, 237));
        txtCustContact1.setBorder(null);
        txtCustContact1.setCaretColor(new java.awt.Color(0, 246, 237));
        txtCustContact1.setOpaque(false);
        txtCustContact1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustContact1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustContact1FocusLost(evt);
            }
        });
        txtCustContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustContact1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtCustContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 400, 400, -1));

        jspContact1.setBackground(new java.awt.Color(255, 250, 255));
        jspContact1.setForeground(new java.awt.Color(255, 250, 255));
        jPanel1.add(jspContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 410, -1));

        txtcustGST1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        txtcustGST1.setForeground(new java.awt.Color(0, 246, 237));
        txtcustGST1.setBorder(null);
        txtcustGST1.setCaretColor(new java.awt.Color(0, 246, 237));
        txtcustGST1.setOpaque(false);
        txtcustGST1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcustGST1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcustGST1FocusLost(evt);
            }
        });
        txtcustGST1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustGST1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtcustGST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 460, 400, -1));

        jspGST1.setBackground(new java.awt.Color(255, 250, 255));
        jspGST1.setForeground(new java.awt.Color(255, 250, 255));
        jPanel1.add(jspGST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 410, -1));

        jScrollPane2.setBackground(new java.awt.Color(29, 35, 59));
        jScrollPane2.setForeground(new java.awt.Color(29, 35, 59));
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtbData1.setBackground(new java.awt.Color(29, 35, 59));
        jtbData1.setFont(new java.awt.Font("Share Tech Mono", 0, 18)); // NOI18N
        jtbData1.setForeground(new java.awt.Color(0, 246, 237));
        jtbData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbData1.setFocusable(false);
        jtbData1.setGridColor(new java.awt.Color(0, 246, 237));
        jtbData1.setOpaque(false);
        jtbData1.setRowHeight(30);
        jtbData1.setRowMargin(2);
        jtbData1.setSelectionBackground(new java.awt.Color(0, 246, 237));
        jtbData1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jtbData1.getTableHeader().setResizingAllowed(false);
        jtbData1.getTableHeader().setReorderingAllowed(false);
        jtbData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbData1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbData1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 710, -1));

        btnUpdate1.setBackground(new java.awt.Color(29, 35, 59));
        btnUpdate1.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(0, 246, 237));
        btnUpdate1.setText(" UPDATE");
        btnUpdate1.setActionCommand("UPDATE");
        btnUpdate1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseExited(evt);
            }
        });
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 760, 140, 50));

        btnDelete1.setBackground(new java.awt.Color(29, 35, 59));
        btnDelete1.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(0, 246, 237));
        btnDelete1.setText(" DELETE");
        btnDelete1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelete1MouseExited(evt);
            }
        });
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 760, 140, 50));

        btnClear1.setBackground(new java.awt.Color(29, 35, 59));
        btnClear1.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnClear1.setForeground(new java.awt.Color(0, 246, 237));
        btnClear1.setText(" CLEAR");
        btnClear1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnClear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear1.setNextFocusableComponent(txtCustName);
        btnClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClear1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClear1MouseExited(evt);
            }
        });
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 760, 140, 50));

        btnAdd1.setBackground(new java.awt.Color(29, 35, 59));
        btnAdd1.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(0, 246, 237));
        btnAdd1.setText(" ADD");
        btnAdd1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdd1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAdd1MouseReleased(evt);
            }
        });
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 760, 140, 50));

        lblName.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 250, 255));
        lblName.setText("Name ");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustEmailActionPerformed

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void txtCustContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustContactActionPerformed

    private void txtcustGSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustGSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustGSTActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String sql = "UPDATE customer SET customername= ? ,contactno= ? , gst = ?, email = ? WHERE customerid = ?";
            
            preparedStatement = conn.prepareStatement(sql);
            
            preparedStatement.setString(1, txtCustName.getText());
            preparedStatement.setString(2, txtCustContact.getText());
            preparedStatement.setString(3, txtcustGST.getText());
            preparedStatement.setString(4, txtCustEmail.getText());
            preparedStatement.setInt(5, Integer.parseInt(selectedCustId));
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully");
            btnAdd.setEnabled(true);
            clearFields();
            
            sql = "SELECT * FROM customer";
            updateTableData(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Issue : " + e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(selectedCustId.equals("")){
                JOptionPane.showMessageDialog(null, "Please select some Recocord to delete!");
        }else{
            int btn = JOptionPane.showConfirmDialog(null, "Do you wanna realluy delete record?", "Delete", JOptionPane.YES_NO_OPTION);
            if(btn == JOptionPane.YES_OPTION){
                try {
                    String sql = "DELETE FROM customer WHERE customerid = ?";
                    preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setString(1, selectedCustId);
                    preparedStatement.execute();
                    JOptionPane.showMessageDialog(null, "Record Deleted Successfully!");
                    
                    btnAdd.setEnabled(true);
                    clearFields();
                    sql = "SELECT * FROM customer";
                    updateTableData(sql);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Delete Issue : " + e);
                }finally{
                    try {
                        preparedStatement.close();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Eroor while closing the statement : " + e);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(txtCustName.getText().equals("") || txtCustContact.getText().equals("") || txtCustEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Some Fields are missing");
        }
        //else if(jspEmail.getBackground()!= Color())
        else{
            String sql = "INSERT INTO customer( customername, contactno, gst, email) VALUES (?,?,?,?)";
            try {
                preparedStatement = conn.prepareStatement(sql);

                preparedStatement.setString(1, txtCustName.getText());
                preparedStatement.setString(2, txtCustContact.getText());
                preparedStatement.setString(3, txtcustGST.getText());
                preparedStatement.setString(4, txtCustEmail.getText());


                boolean stmt = preparedStatement.execute();
                //JOptionPane.showMessageDialog(null, "Record Saved Successfully"); 

                sql = "SELECT * FROM customer";
                updateTableData(sql);

                clearFields();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Some Error : " + e);            
            } 
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jtbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDataMouseClicked
        btnAdd.setEnabled(false);
        selectedRow = jtbData.getSelectedRow();
        selectedCustId = jtbData.getModel().getValueAt(selectedRow, 0).toString();
        try {
            sql = "SELECT * FROM customer WHERE customerid = " + selectedCustId;
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            if(rs.next()){
                txtCustName.setText(rs.getString("customername"));
                txtCustContact.setText(rs.getString("contactno"));
                txtcustGST.setText(rs.getString("gst"));
                txtCustEmail.setText(rs.getString("email"));
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Some Error : " + e);
        }
    }//GEN-LAST:event_jtbDataMouseClicked

    private void btnAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddMousePressed

    private void btnAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseReleased
        
    }//GEN-LAST:event_btnAddMouseReleased

    private void txtCustNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustNameFocusGained
        jspName.setBackground(Constants.LIGHT_BLUE);
        jspName.setForeground(Constants.LIGHT_BLUE);
        lblName.setForeground(Constants.LIGHT_BLUE);
    }//GEN-LAST:event_txtCustNameFocusGained

    private void txtCustNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustNameFocusLost
        jspName.setBackground(Constants.WHITE);
        jspName.setForeground(Constants.WHITE);
        lblName.setForeground(Constants.WHITE);
    }//GEN-LAST:event_txtCustNameFocusLost

    private void txtCustContactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustContactFocusGained
        jspContact.setBackground(Constants.LIGHT_BLUE);
        jspContact.setForeground(Constants.LIGHT_BLUE);
        lblCustContact.setForeground(Constants.LIGHT_BLUE);
    }//GEN-LAST:event_txtCustContactFocusGained

    private void txtCustContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustContactFocusLost
       jspContact.setBackground(Constants.WHITE);
       jspContact.setForeground(Constants.WHITE);
       lblCustContact.setForeground(Constants.WHITE);
    }//GEN-LAST:event_txtCustContactFocusLost

    private void txtcustGSTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcustGSTFocusGained
        jspGST.setBackground(Constants.LIGHT_BLUE);
        jspGST.setForeground(Constants.LIGHT_BLUE);
        lblCustGST.setForeground(Constants.LIGHT_BLUE);
    }//GEN-LAST:event_txtcustGSTFocusGained

    private void txtcustGSTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcustGSTFocusLost
        jspGST.setBackground(Constants.WHITE);
        jspGST.setForeground(Constants.WHITE);
        lblCustGST.setForeground(Constants.WHITE);
    }//GEN-LAST:event_txtcustGSTFocusLost

    private void txtCustEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustEmailFocusGained
        jspEmail.setBackground(Constants.LIGHT_BLUE);
        jspEmail.setForeground(Constants.LIGHT_BLUE);
        lblCustEmail.setForeground(Constants.LIGHT_BLUE);
    }//GEN-LAST:event_txtCustEmailFocusGained

    private void txtCustEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustEmailFocusLost
        jspEmail.setBackground(Constants.WHITE);
        jspEmail.setForeground(Constants.WHITE);
        lblCustEmail.setForeground(Constants.WHITE);
    }//GEN-LAST:event_txtCustEmailFocusLost

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBackground(Constants.LIGHT_BLUE);
        btnAdd.setForeground(Constants.ACCENT_BLUE);
        btnAdd.setIcon(IconFontSwing.buildIcon(Constants.addButton, 30, Constants.ACCENT_BLUE));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setBackground(Constants.ACCENT_BLUE);
        btnAdd.setForeground(Constants.LIGHT_BLUE);
        btnAdd.setIcon(IconFontSwing.buildIcon(Constants.addButton, 30, Constants.LIGHT_BLUE));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        btnUpdate.setBackground(Constants.LIGHT_BLUE);
        btnUpdate.setForeground(Constants.ACCENT_BLUE);
        btnUpdate.setIcon(IconFontSwing.buildIcon(Constants.updateButton, 30, Constants.ACCENT_BLUE));
        
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(Constants.LIGHT_BLUE);
        btnDelete.setForeground(Constants.ACCENT_BLUE);
        btnDelete.setIcon(IconFontSwing.buildIcon(Constants.deleteButton, 30, Constants.ACCENT_BLUE));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        btnClear.setBackground(Constants.LIGHT_BLUE);
        btnClear.setForeground(Constants.ACCENT_BLUE);
        btnClear.setIcon(IconFontSwing.buildIcon(Constants.clearButton, 30, Constants.ACCENT_BLUE));
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        btnUpdate.setBackground(Constants.ACCENT_BLUE);
        btnUpdate.setForeground(Constants.LIGHT_BLUE);
        btnUpdate.setIcon(IconFontSwing.buildIcon(Constants.updateButton, 30, Constants.LIGHT_BLUE));
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setBackground(Constants.ACCENT_BLUE);
        btnDelete.setForeground(Constants.LIGHT_BLUE);
        btnDelete.setIcon(IconFontSwing.buildIcon(Constants.deleteButton, 30, Constants.LIGHT_BLUE));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        btnClear.setBackground(Constants.ACCENT_BLUE);
        btnClear.setForeground(Constants.LIGHT_BLUE);
        btnClear.setIcon(IconFontSwing.buildIcon(Constants.clearButton, 30, Constants.LIGHT_BLUE));
    }//GEN-LAST:event_btnClearMouseExited

    private void txtCustEmail1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustEmail1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustEmail1FocusGained

    private void txtCustEmail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustEmail1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustEmail1FocusLost

    private void txtCustEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustEmail1ActionPerformed

    private void txtCustName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustName1FocusGained

    private void txtCustName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustName1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustName1FocusLost

    private void txtCustName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustName1ActionPerformed

    private void txtCustContact1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustContact1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustContact1FocusGained

    private void txtCustContact1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustContact1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustContact1FocusLost

    private void txtCustContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustContact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustContact1ActionPerformed

    private void txtcustGST1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcustGST1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustGST1FocusGained

    private void txtcustGST1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcustGST1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustGST1FocusLost

    private void txtcustGST1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustGST1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustGST1ActionPerformed

    private void jtbData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbData1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbData1MouseClicked

    private void btnUpdate1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1MouseEntered

    private void btnUpdate1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1MouseExited

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1MouseEntered

    private void btnDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1MouseExited

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnClear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1MouseEntered

    private void btnClear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1MouseExited

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnAdd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MouseEntered

    private void btnAdd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MouseExited

    private void btnAdd1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MousePressed

    private void btnAdd1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MouseReleased

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jspContact;
    private javax.swing.JSeparator jspContact1;
    private javax.swing.JSeparator jspEmail;
    private javax.swing.JSeparator jspEmail1;
    private javax.swing.JSeparator jspGST;
    private javax.swing.JSeparator jspGST1;
    private javax.swing.JSeparator jspName;
    private javax.swing.JSeparator jspName1;
    private javax.swing.JTable jtbData;
    private javax.swing.JTable jtbData1;
    private javax.swing.JLabel lblCustContact;
    private javax.swing.JLabel lblCustContact1;
    private javax.swing.JLabel lblCustEmail;
    private javax.swing.JLabel lblCustEmail1;
    private javax.swing.JLabel lblCustGST;
    private javax.swing.JLabel lblCustGST1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblcust;
    private javax.swing.JTextField txtCustContact;
    private javax.swing.JTextField txtCustContact1;
    private javax.swing.JTextField txtCustEmail;
    private javax.swing.JTextField txtCustEmail1;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustName1;
    private javax.swing.JTextField txtcustGST;
    private javax.swing.JTextField txtcustGST1;
    // End of variables declaration//GEN-END:variables
    private Connection conn = null;
    private PreparedStatement preparedStatement = null;
    private ResultSet rs = null;
    private String sql = null;
    private int selectedRow;
    private String selectedCustId;
}
