
import java.awt.Toolkit;
import java.awt.event.WindowEvent;



/*
 * COLOR SCHEME USED : https://coolors.co/363537-0cce6b-dced31-ef2d56-00f6ed
 */
/**
 *
 * @author shubham
 */
public class Dashboard extends javax.swing.JFrame implements Constants {

    /**
     * Creates new form Dashboard
     */
    public Dashboard(int CUSTOMER_TYPE) {
        initComponents();
        cf = new CustomerForm();
        sf = new StockForm();
        mp = new MainPanel();
        sales = new SalesForm();
        rf = new ReportsForm();
        
        centerPanel.add(mp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 1080));
        mp.setVisible(true);
        this.pack();
        
        if(CUSTOMER_TYPE == EMPLOYEE) {
            btnCustomer.setVisible(false);
            btnHome.setVisible(false);
            btnStocks.setVisible(false);
            btnReports.setVisible(false);
            centerPanel.removeAll();
            centerPanel.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 1080));
            sales.setVisible(true);
            sales.refreshProductNames();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolPanel = new javax.swing.JPanel();
        btnStocks = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JLabel();
        btnSales = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        btnReports = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stockpile Management");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1919, 1030));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolPanel.setBackground(new java.awt.Color(54, 53, 55));
        toolPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory logos/stocks.png"))); // NOI18N
        btnStocks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStocksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStocksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStocksMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStocksMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStocksMouseReleased(evt);
            }
        });
        toolPanel.add(btnStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 560, 70, 70));

        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory logos/customer.png"))); // NOI18N
        btnCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCustomerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCustomerMouseReleased(evt);
            }
        });
        toolPanel.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 320, 70, 70));

        btnSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory logos/sales.png"))); // NOI18N
        btnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSalesMouseReleased(evt);
            }
        });
        toolPanel.add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 440, 70, 70));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory logos/home.png"))); // NOI18N
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
        });
        toolPanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 200, -1, -1));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory logos/logout.png"))); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogoutMouseReleased(evt);
            }
        });
        toolPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 880, -1, -1));

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventory logos/reports.png"))); // NOI18N
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReportsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReportsMouseReleased(evt);
            }
        });
        toolPanel.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 680, 70, 70));

        getContentPane().add(toolPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 1050));

        centerPanel.setBackground(new java.awt.Color(29, 35, 59));
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, 1820, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseEntered
        btnCustomer.setIcon(CUSTOMER_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnCustomerMouseEntered

    private void btnCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseExited
        btnCustomer.setIcon(CUSTOMER_BUTTON);
    }//GEN-LAST:event_btnCustomerMouseExited

    private void btnCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseClicked
        centerPanel.removeAll();
        centerPanel.add(cf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 1080));
        this.pack();
        cf.validate();
        centerPanel.validate();
        cf.setVisible(true);
        sql = "SELECT * FROM customer";
        cf.updateTableData(sql);
        sf.setVisible(false);
        rf.setVisible(false);
        sales.setVisible(false);
        mp.setVisible(false);
    }//GEN-LAST:event_btnCustomerMouseClicked

    private void btnCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMousePressed
        btnCustomer.setIcon(CUSTOMER_BUTTON_PRESSED);

    }//GEN-LAST:event_btnCustomerMousePressed

    private void btnCustomerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerMouseReleased
        btnCustomer.setIcon(CUSTOMER_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnCustomerMouseReleased

    private void btnSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseEntered
        btnSales.setIcon(SALES_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnSalesMouseEntered

    private void btnSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseExited
        btnSales.setIcon(SALES_BUTTON);
    }//GEN-LAST:event_btnSalesMouseExited

    private void btnSalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMousePressed
        btnSales.setIcon(SALES_BUTTON_PRESSED);
    }//GEN-LAST:event_btnSalesMousePressed

    private void btnSalesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseReleased
        btnSales.setIcon(SALES_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnSalesMouseReleased

    private void btnStocksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStocksMouseEntered
        btnStocks.setIcon(STOCKS_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnStocksMouseEntered

    private void btnStocksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStocksMouseExited
        btnStocks.setIcon(STOCKS_BUTTON);
    }//GEN-LAST:event_btnStocksMouseExited

    private void btnStocksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStocksMousePressed
        btnStocks.setIcon(STOCKS_BUTTON_PRESSED);
    }//GEN-LAST:event_btnStocksMousePressed

    private void btnStocksMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStocksMouseReleased
        btnStocks.setIcon(STOCKS_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnStocksMouseReleased

    private void btnStocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStocksMouseClicked
        centerPanel.removeAll();
        centerPanel.add(sf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 1080));
        sf.setVisible(true);
        sql = "SELECT productid, productname, mass, mrp, stock FROM product";
        sf.updateTableData(sql);
        sf.refreshAddCategory();
        cf.setVisible(false);
        sales.setVisible(false);
        rf.setVisible(false);
        mp.setVisible(false);
        this.pack();
    }//GEN-LAST:event_btnStocksMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        centerPanel.removeAll();
        centerPanel.add(mp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 1080));
        mp.setVisible(true);
        mp.barChartDemo();
        mp.updateLists();
        sales.setVisible(false);
        sf.setVisible(false);
        cf.setVisible(false);
        rf.setVisible(false);
        this.pack();                
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setIcon(HOME_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setIcon(HOME_BUTTON);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        btnHome.setIcon(HOME_BUTTON_PRESSED);
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        btnHome.setIcon(HOME_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnHomeMouseReleased

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setIcon(LOGOUT_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setIcon(LOGOUT_BUTTON);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        btnLogout.setIcon(LOGOUT_BUTTON_PRESSED);
    }//GEN-LAST:event_btnLogoutMousePressed

    private void btnLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseReleased
        btnLogout.setIcon(LOGOUT_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnLogoutMouseReleased

    private void btnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesMouseClicked
        centerPanel.removeAll();
        centerPanel.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 1080));
        sales.setVisible(true);
//        sales.refreshCustomerNames();
        sales.refreshProductNames();
        mp.setVisible(false);
        sf.setVisible(false);
        rf.setVisible(false);
        cf.setVisible(false);
        this.pack();  
    }//GEN-LAST:event_btnSalesMouseClicked

    private void btnReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseClicked
        btnReports.setIcon(REPORTS_BUTTON_PRESSED);
        centerPanel.removeAll();
        
        centerPanel.add(rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1820, 1080));
        mp.setVisible(false);
        sf.setVisible(false);
        cf.setVisible(false);
        rf.setVisible(true);
        this.pack();
        rf.revalidate();
    }//GEN-LAST:event_btnReportsMouseClicked

    private void btnReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseEntered
        btnReports.setIcon(REPORTS_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnReportsMouseEntered

    private void btnReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseExited
        btnReports.setIcon(REPORTS_BUTTON);
    }//GEN-LAST:event_btnReportsMouseExited

    private void btnReportsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMousePressed
        btnReports.setIcon(REPORTS_BUTTON_PRESSED);
    }//GEN-LAST:event_btnReportsMousePressed

    private void btnReportsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseReleased
        btnReports.setIcon(REPORTS_BUTTON_ROLLOVER);
    }//GEN-LAST:event_btnReportsMouseReleased

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(1).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnReports;
    private javax.swing.JLabel btnSales;
    private javax.swing.JLabel btnStocks;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel toolPanel;
    // End of variables declaration//GEN-END:variables
    private CustomerForm cf;
    private StockForm sf;
    private MainPanel mp;
    private SalesForm sales;
    private ReportsForm rf;
    private String sql = null;
}
