
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jiconfont.swing.IconFontSwing;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        pieChartDemo();
        barChartDemo();
//        btnRightShift.setIcon(IconFontSwing.buildIcon(Constants.rightShift, 24, new Color(0,246,237)));
        conn = MySqlConnect.connectDB();
        updateLists();
        btnAdd.setIcon(IconFontSwing.buildIcon(Constants.rightShift, 30, Constants.LIGHT_BLUE));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void pieChartDemo() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Amul BUtter", new Double(20));
        dataset.setValue("Pineapple Syrup", new Double(40));
        dataset.setValue("Amul cheeze", new Double(20));
        dataset.setValue("Raasna", new Double(70));
        JFreeChart chart = ChartFactory.createPieChart("", dataset, false, true, false);

        ChartPanel cp = new ChartPanel(chart);

        PiePlot pp = (PiePlot) chart.getPlot();
        
        Font f = new Font("Arial", 1, 14);
        pp.setLabelFont(f);
        pp.setLabelLinkPaint(Constants.LIGHT_BLUE);
        pp.setSectionPaint(1, new Color(12, 206, 107));
        pp.setSectionPaint(2, new Color(220, 237, 49));
        pp.setSectionPaint(3, new Color(239, 45, 86));
        pp.setSectionPaint(4, new Color(0, 246, 237));
        pp.setBackgroundPaint(new Color(29, 35, 59));
        pp.setOutlinePaint(new Color(29, 35, 59));
        pp.setLabelPaint(new Color(0, 246, 237));
        pp.setLabelBackgroundPaint(null);
        pp.setLabelShadowPaint(null);
        pp.setLabelOutlinePaint(null);
        pp.setShadowPaint(null);
        chart.setBackgroundPaint(new Color(29, 35, 59));
        cp.setSize(200,200);
        //Bar chart border color
        //chart.getXYPlot().getRenderer().setSeriesPaint(1, new Color(29,35,59));
        cp.setBorder(null);
        pnlPieChartDemo.add(cp);
    }

    public void barChartDemo(){
        try {
            pnlBarChartDemo.removeAll();
            String sql = "SELECT productname,stock from product WHERE stock < 15 ";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(MySqlConnect.connectDB(), sql);

             JFreeChart barChart;

             barChart = ChartFactory.createBarChart("", "Product Name", "Stock", dataset, PlotOrientation.VERTICAL, false, true, true);
             ChartPanel cp = new ChartPanel(barChart);
             pnlBarChartDemo.add(cp);
             CategoryPlot p = (CategoryPlot) barChart.getPlot();
             BarRenderer renderer = (BarRenderer) p.getRenderer();
             renderer.setBarPainter(new StandardBarPainter());
             renderer.setSeriesPaint(0, new Color(12, 206, 107));
             renderer.setSeriesPaint(1, new Color(220, 237, 49));
             renderer.setSeriesPaint(2, new Color(239, 45, 86));

             p.getDomainAxis().setTickLabelPaint(Constants.LIGHT_BLUE);
             p.getDomainAxis().setAxisLinePaint(Constants.LIGHT_BLUE);
             p.getDomainAxis().setLabelPaint(Constants.LIGHT_BLUE);

             p.getRangeAxis().setTickLabelPaint(Constants.LIGHT_BLUE);
             p.getRangeAxis().setAxisLinePaint(Constants.LIGHT_BLUE);
             p.getRangeAxis().setLabelPaint(Constants.LIGHT_BLUE);
             Font f = new Font("Arial", 1, 18);
             p.getRangeAxis().setLabelFont(f);
             p.setRangeGridlinePaint(new Color(0, 246, 237));
             p.setBackgroundPaint(new Color(29, 35, 59));
             barChart.setBackgroundPaint(new Color(29, 35, 59));
             p.setOutlinePaint(new Color(29, 35, 59));
             barChart.removeLegend();
        } catch (Exception e) {
            System.out.println("Some error in bar chart : " + e);
        }

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlBarChartDemo = new javax.swing.JPanel();
        pnlPieChartDemo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblcust = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlCleared = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlPending = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1820, 1050));

        mainPanel.setBackground(new java.awt.Color(29, 35, 59));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 35, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarChartDemo.setBackground(new java.awt.Color(29, 35, 59));
        jPanel1.add(pnlBarChartDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 890, 490));

        pnlPieChartDemo.setBackground(new java.awt.Color(29, 35, 59));
        jPanel1.add(pnlPieChartDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 620, 480));

        jLabel2.setBackground(new java.awt.Color(0, 246, 237));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 246, 237));
        jLabel2.setText("Product Stocks");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 246, 237));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 246, 237));
        jLabel1.setText("Product Sales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        lblcust.setFont(new java.awt.Font("Share Tech Mono", 0, 55)); // NOI18N
        lblcust.setForeground(new java.awt.Color(255, 250, 255));
        lblcust.setText("Dashboard ");
        mainPanel.add(lblcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 550, 190));

        jlCleared.setBackground(new java.awt.Color(29, 35, 59));
        jlCleared.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        jlCleared.setForeground(new java.awt.Color(0, 246, 237));
        jlCleared.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jlCleared.setFillsViewportHeight(true);
        jlCleared.setRowHeight(25);
        jScrollPane1.setViewportView(jlCleared);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 790, -1, 170));

        jlPending.setBackground(new java.awt.Color(29, 35, 59));
        jlPending.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        jlPending.setForeground(new java.awt.Color(0, 246, 237));
        jlPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jlPending.setFillsViewportHeight(true);
        jlPending.setRowHeight(25);
        jScrollPane4.setViewportView(jlPending);

        mainPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 790, -1, 170));

        btnAdd.setBackground(new java.awt.Color(29, 35, 59));
        btnAdd.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 246, 237));
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        mainPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 840, 60, 60));

        jLabel3.setBackground(new java.awt.Color(0, 246, 237));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 246, 237));
        jLabel3.setText("Cleared Cheques");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 750, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 246, 237));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 246, 237));
        jLabel4.setText("Pending Cheques");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 750, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1820, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1101, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBackground(Constants.LIGHT_BLUE);
        btnAdd.setForeground(Constants.ACCENT_BLUE);
        btnAdd.setIcon(IconFontSwing.buildIcon(Constants.rightShift, 30, Constants.ACCENT_BLUE));
        
        
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // TODO add your handling code here:
        btnAdd.setBackground(Constants.ACCENT_BLUE);
        btnAdd.setForeground(Constants.LIGHT_BLUE);
        btnAdd.setIcon(IconFontSwing.buildIcon(Constants.rightShift, 30, Constants.LIGHT_BLUE));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int id = (Integer)jlPending.getModel().getValueAt(jlPending.getSelectedRow(),0);
        try {
            preparedStatement = conn.prepareStatement("UPDATE cheque_info SET status = 1 WHERE bill_id = '" + id  +"'");
            preparedStatement.execute();
            updateLists();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddActionPerformed
    public void updateLists() {
        try {
            
            preparedStatement = conn.prepareStatement("SELECT bill_id,chequenum FROM cheque_info WHERE status = '0'");
            rs = preparedStatement.executeQuery();
            System.out.println("rs " + rs);
            jlPending.setModel(DbUtils.resultSetToTableModel(rs));
            preparedStatement = conn.prepareStatement("SELECT bill_id,chequenum FROM cheque_info WHERE status = 1");
            rs = preparedStatement.executeQuery();
            jlCleared.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Error in update list : " + e);
        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jlCleared;
    private javax.swing.JTable jlPending;
    private javax.swing.JLabel lblcust;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlBarChartDemo;
    private javax.swing.JPanel pnlPieChartDemo;
    // End of variables declaration//GEN-END:variables

    private PreparedStatement preparedStatement;
    private ResultSet rs;
    private Connection conn;
}
