
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubham
 */
public class ReportsForm extends javax.swing.JPanel {

    /**
     * Creates new form RepotsPnl
     */
    public ReportsForm() {
        initComponents();

    }
    private void updateTable() {
        try {
            Connection conn = MySqlConnect.connectDB();
            PreparedStatement preparedStatement = conn.prepareStatement("SELECT billid,date,cgst,sgst,igst,total FROM bill WHERE date >= ? AND date <= ?");
            preparedStatement.setString(1,new SimpleDateFormat("dd-MM-yyyy").format(jcStart.getDate()));
            preparedStatement.setString(2,new SimpleDateFormat("dd-MM-yyyy").format(jcEnd.getDate()));
            ResultSet rs = preparedStatement.executeQuery();
            jTable.setModel(DbUtils.resultSetToTableModel(rs));
            preparedStatement = conn.prepareStatement("SELECT SUM(cgst) AS CGSTSUM, SUM(sgst) AS SGSTSUM,SUM(igst) AS IGSTSUM, SUM(total) AS TOTAL FROM bill WHERE date >= ? AND date <= ?");
            preparedStatement.setString(1,new SimpleDateFormat("dd-MM-yyyy").format(jcStart.getDate()));
            preparedStatement.setString(2,new SimpleDateFormat("dd-MM-yyyy").format(jcEnd.getDate()));
            rs = preparedStatement.executeQuery();
            rs.next();
            
            String s = rs.getString("CGSTSUM");
            lblCgst.setText(s);
            lblSgst.setText(rs.getString("SGSTSUM"));
            lblIgst.setText(rs.getString("IGSTSUM"));
            lblTotal.setText(rs.getString("TOTAL"));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR IN UPDATING TABLE : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jcEnd = new com.toedter.calendar.JDateChooser();
        jcStart = new com.toedter.calendar.JDateChooser();
        lblProductName = new javax.swing.JLabel();
        lblProductName1 = new javax.swing.JLabel();
        lblcust = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblCgst = new javax.swing.JLabel();
        lblSgst = new javax.swing.JLabel();
        lblIgst = new javax.swing.JLabel();

        setBackground(new java.awt.Color(29, 35, 59));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setBackground(new java.awt.Color(29, 35, 59));
        jTable.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        jTable.setForeground(new java.awt.Color(0, 246, 237));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "billid", "date", "cgst", "sgst", "igst", "total"
            }
        ));
        jTable.setFillsViewportHeight(true);
        jTable.setRowHeight(26);
        jScrollPane1.setViewportView(jTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1780, 530));
        add(jcEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 171, 30));
        add(jcStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 171, 31));

        lblProductName.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 250, 255));
        lblProductName.setText("To :");
        add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        lblProductName1.setFont(new java.awt.Font("Share Tech Mono", 0, 24)); // NOI18N
        lblProductName1.setForeground(new java.awt.Color(255, 250, 255));
        lblProductName1.setText("From :");
        add(lblProductName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        lblcust.setFont(new java.awt.Font("Share Tech Mono", 0, 55)); // NOI18N
        lblcust.setForeground(new java.awt.Color(255, 250, 255));
        lblcust.setText("Reports");
        add(lblcust, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 240, 190));

        btnAdd.setBackground(new java.awt.Color(29, 35, 59));
        btnAdd.setFont(new java.awt.Font("Share Tech Mono", 0, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 246, 237));
        btnAdd.setText("GO");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 246, 237), 1, true));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 240, 60, 30));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 246, 237));
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 910, 100, 50));

        lblCgst.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lblCgst.setForeground(new java.awt.Color(0, 246, 237));
        add(lblCgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 890, 100, 50));

        lblSgst.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lblSgst.setForeground(new java.awt.Color(0, 246, 237));
        add(lblSgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 900, 100, 50));

        lblIgst.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lblIgst.setForeground(new java.awt.Color(0, 246, 237));
        add(lblIgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 900, 100, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBackground(Constants.LIGHT_BLUE);
        btnAdd.setForeground(Constants.ACCENT_BLUE);
        
     
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setBackground(Constants.ACCENT_BLUE);
        btnAdd.setForeground(Constants.LIGHT_BLUE);
       
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        updateTable();
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private com.toedter.calendar.JDateChooser jcEnd;
    private com.toedter.calendar.JDateChooser jcStart;
    private javax.swing.JLabel lblCgst;
    private javax.swing.JLabel lblIgst;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductName1;
    private javax.swing.JLabel lblSgst;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblcust;
    // End of variables declaration//GEN-END:variables
}
